# Generated by Django 4.0.2 on 2023-02-05 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='utilizador.categoria')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='utilizador.genero')),
                ('data_nascimento', models.CharField(blank=True, max_length=20, null=True)),
                ('ndi', models.CharField(blank=True, max_length=40, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, default='user.jpg', null=True, upload_to='user/%d-%m-%y/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
