# Generated by Django 4.0.2 on 2023-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0003_utilizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='foto',
            field=models.ImageField(blank=True, default='user.jpg', null=True, upload_to='uploads/%d-%m-%y/'),
        ),
    ]
