# Generated by Django 4.0.2 on 2023-02-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0005_alter_utilizador_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='categoria',
        ),
    ]
