# Generated by Django 4.0.2 on 2023-02-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0006_remove_utilizador_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
