# Generated by Django 4.0.2 on 2023-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0007_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='estadoPassword',
            field=models.BooleanField(default=False),
        ),
    ]
