# Generated by Django 4.0.2 on 2023-03-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0009_utilizador_slug_alter_utilizador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.permission')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
