# Generated by Django 4.0.2 on 2023-03-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0010_permissao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissao',
        ),
    ]
