# Generated by Django 4.0.2 on 2023-03-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0011_delete_permissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissao_Nao_Visivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='contenttypes.contenttype')),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
