# Generated by Django 4.0.2 on 2023-02-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_categoria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='data',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='estado',
        ),
    ]
