# Generated by Django 4.0.2 on 2023-02-05 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_alter_imagem_arquivos_alter_imagem_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, parent_link=True, to='bug.estadobug')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='bug.categoria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='bug.tipo')),
                ('dataPublicacao', models.DateField()),
                ('descricao', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
