# Generated by Django 4.0.2 on 2023-02-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='bug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='bug.bug'),
        ),
    ]
