# Generated by Django 4.0.2 on 2023-02-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0007_imagem_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='descricao',
            field=models.TextField(),
        ),
    ]
