# Generated by Django 4.0.2 on 2023-02-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0008_alter_imagem_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='descricao',
            new_name='content',
        ),
    ]
