# Generated by Django 4.0.2 on 2023-02-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0010_bug_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='bug',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True),
        ),
    ]
