# Generated by Django 4.0.2 on 2023-03-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0011_alter_bug_options_alter_bug_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='bug',
        ),
    ]
