# Generated by Django 4.0.2 on 2023-03-17 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0013_imagem_autor_imagem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='dataPublicacao',
            field=models.DateField(default=datetime.date(2023, 3, 17)),
        ),
    ]
