# Generated by Django 4.0.2 on 2023-03-18 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0014_imagem_datapublicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='bug.bug')),
                ('slug', models.SlugField(blank=True, max_length=400, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/arquivo/%d-%m-%yyyy/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to='uploads/imagem/%d-%m-%yyyy/'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='dataPublicacao',
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
    ]
