# Generated by Django 4.0.2 on 2023-03-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0016_alter_imagem_datapublicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='dataPublicacao',
            field=models.DateField(),
        ),
    ]
