# Generated by Django 4.0.2 on 2023-02-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('dataPublicacao', models.DateField()),
                ('descricao', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=400, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem/%d-%m-%yyyy/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
